// Code generated by "stringer -type Kind"; DO NOT EDIT.

package msgs

import "fmt"

const _Kind_name = "DataByteNoteOffNoteOnKeyPressureControlChangeProgramChangeChannelPressurePitchBendSystemExclusiveSystemCommonTimeCodeSystemCommonSongPositionPointerSystemCommonSongSelectSystemCommonUndefinedSystemCommonTuneRequestSystemCommonEOXRealTime"

var _Kind_index = [...]uint8{0, 8, 15, 21, 32, 45, 58, 73, 82, 97, 117, 148, 170, 191, 214, 229, 237}

func (i Kind) String() string {
	if i >= Kind(len(_Kind_index)-1) {
		return fmt.Sprintf("Kind(%d)", i)
	}
	return _Kind_name[_Kind_index[i]:_Kind_index[i+1]]
}
