package nanokontrol

func ControlIDFromName(name string) ControlID {
	switch name {
	case "Slider1":
		return Slider1
	case "Slider2":
		return Slider2
	case "Slider3":
		return Slider3
	case "Slider4":
		return Slider4
	case "Slider5":
		return Slider5
	case "Slider6":
		return Slider6
	case "Slider7":
		return Slider7
	case "Slider8":
		return Slider8
	case "Knob1":
		return Knob1
	case "Knob2":
		return Knob2
	case "Knob3":
		return Knob3
	case "Knob4":
		return Knob4
	case "Knob5":
		return Knob5
	case "Knob6":
		return Knob6
	case "Knob7":
		return Knob7
	case "Knob8":
		return Knob8
	case "SoloButton1":
		return SoloButton1
	case "SoloButton2":
		return SoloButton2
	case "SoloButton3":
		return SoloButton3
	case "SoloButton4":
		return SoloButton4
	case "SoloButton5":
		return SoloButton5
	case "SoloButton6":
		return SoloButton6
	case "SoloButton7":
		return SoloButton7
	case "SoloButton8":
		return SoloButton8
	case "PlayButton":
		return PlayButton
	case "StopButton":
		return StopButton
	case "Rewind":
		return Rewind
	case "FastForward":
		return FastForward
	case "Record":
		return Record
	case "Cycle":
		return Cycle
	case "MuteButton1":
		return MuteButton1
	case "MuteButton2":
		return MuteButton2
	case "MuteButton3":
		return MuteButton3
	case "MuteButton4":
		return MuteButton4
	case "MuteButton5":
		return MuteButton5
	case "MuteButton6":
		return MuteButton6
	case "MuteButton7":
		return MuteButton7
	case "MuteButton8":
		return MuteButton8
	case "TrackLeft":
		return TrackLeft
	case "TrackRight":
		return TrackRight
	case "MarkerSet":
		return MarkerSet
	case "MarkerLeft":
		return MarkerLeft
	case "MarkerRight":
		return MarkerRight
	case "RecordButton1":
		return RecordButton1
	case "RecordButton2":
		return RecordButton2
	case "RecordButton3":
		return RecordButton3
	case "RecordButton4":
		return RecordButton4
	case "RecordButton5":
		return RecordButton5
	case "RecordButton6":
		return RecordButton6
	case "RecordButton7":
		return RecordButton7
	case "RecordButton8":
		return RecordButton8
	}
	return 255
}
