// Code generated by "stringer -type=ControlID"; DO NOT EDIT.

package nanokontrol

import "fmt"

const (
	_ControlID_name_0 = "Slider1Slider2Slider3Slider4Slider5Slider6Slider7Slider8"
	_ControlID_name_1 = "Knob1Knob2Knob3Knob4Knob5Knob6Knob7Knob8"
	_ControlID_name_2 = "SoloButton1SoloButton2SoloButton3SoloButton4SoloButton5SoloButton6SoloButton7SoloButton8"
	_ControlID_name_3 = "PlayButtonStopButtonRewindFastForwardRecordCycle"
	_ControlID_name_4 = "MuteButton1MuteButton2MuteButton3MuteButton4MuteButton5MuteButton6MuteButton7MuteButton8"
	_ControlID_name_5 = "TrackLeftTrackRightMarkerSetMarkerLeftMarkerRight"
	_ControlID_name_6 = "RecordButton1RecordButton2RecordButton3RecordButton4RecordButton5RecordButton6RecordButton7RecordButton8"
)

var (
	_ControlID_index_0 = [...]uint8{0, 7, 14, 21, 28, 35, 42, 49, 56}
	_ControlID_index_1 = [...]uint8{0, 5, 10, 15, 20, 25, 30, 35, 40}
	_ControlID_index_2 = [...]uint8{0, 11, 22, 33, 44, 55, 66, 77, 88}
	_ControlID_index_3 = [...]uint8{0, 10, 20, 26, 37, 43, 48}
	_ControlID_index_4 = [...]uint8{0, 11, 22, 33, 44, 55, 66, 77, 88}
	_ControlID_index_5 = [...]uint8{0, 9, 19, 28, 38, 49}
	_ControlID_index_6 = [...]uint8{0, 13, 26, 39, 52, 65, 78, 91, 104}
)

func (i ControlID) String() string {
	switch {
	case 0 <= i && i <= 7:
		return _ControlID_name_0[_ControlID_index_0[i]:_ControlID_index_0[i+1]]
	case 16 <= i && i <= 23:
		i -= 16
		return _ControlID_name_1[_ControlID_index_1[i]:_ControlID_index_1[i+1]]
	case 32 <= i && i <= 39:
		i -= 32
		return _ControlID_name_2[_ControlID_index_2[i]:_ControlID_index_2[i+1]]
	case 41 <= i && i <= 46:
		i -= 41
		return _ControlID_name_3[_ControlID_index_3[i]:_ControlID_index_3[i+1]]
	case 48 <= i && i <= 55:
		i -= 48
		return _ControlID_name_4[_ControlID_index_4[i]:_ControlID_index_4[i+1]]
	case 58 <= i && i <= 62:
		i -= 58
		return _ControlID_name_5[_ControlID_index_5[i]:_ControlID_index_5[i+1]]
	case 64 <= i && i <= 71:
		i -= 64
		return _ControlID_name_6[_ControlID_index_6[i]:_ControlID_index_6[i+1]]
	default:
		return fmt.Sprintf("ControlID(%d)", i)
	}
}
