// Code generated by "stringer -type Device"; DO NOT EDIT.

package korgdevices

import "fmt"

const _Device_name = "NanoKONTROL2"

var _Device_index = [...]uint8{0, 12}

func (i Device) String() string {
	i -= 275
	if i >= Device(len(_Device_index)-1) {
		return fmt.Sprintf("Device(%d)", i+275)
	}
	return _Device_name[_Device_index[i]:_Device_index[i+1]]
}
